language: python
jobs:
  include:
    - os: linux
      python: 3.8
      env: TOXENY=py38
    - os: osx
      python: 3.9
      env: TOXENY=py39
    - os: windows
      language: shell # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip install -r requirements.txt 
# command to run tests
script: python3 main.py
